### ISSUE TITLE
Wrong date handling

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#10]
How do we handle wrong date like this one in petit bulletin?
https://www.petit-bulletin.fr/lyon/agenda-308615-ayron-jones-amongst-liars.html

The date is wrong on petit bulletin (Du 13 février au 12 mars 2024, à 20h) and then gets also wrong in whatnext (2 Fevrier)

Ayron Jones + Amongst Liars is playing le 13 fevrier au final

**Comment by tnguyenh** [comment]
already in issue #4
