### ISSUE TITLE
Remove duplicates events from different sources

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/WhatsNext#11]
We have to define the process to remove duplicates. 

For places for which scrapex scraps the dedicated site (eg: Transbordeur), we can assume that events are fully and correctly listed there. Unless some other sites provide better info, I propose to skip events from other sources: eg, events from Petit Bulletin for Transbordeur will be skipped.

For places with no dedicated site scrapped, some priority order and way to process the events should be defined.

**Comment by tnguyenh** [comment]
Some issues for merging:

not exactly the same name:
![image](https://github.com/agrignard/WhatsNext/assets/18676913/dd8a9a00-5647-4cba-acb7-4b9b47f282c1)

![image](https://github.com/agrignard/WhatsNext/assets/18676913/8047ea03-9fad-4bbb-b97a-3ccde26a2b8d)


not the same time:
![image](https://github.com/agrignard/WhatsNext/assets/18676913/97f18406-96f9-408e-a5a2-11a40a7e1c15)

**Comment by agrignard** [comment]
J'ai fait une grosse passe sur les events généré pour identifier les probleme avec les places y'a à mon avis une discussion à avoir en line avec cette issue
https://github.com/agrignard/WhatsNext/issues/18

**Comment by tnguyenh** [comment]
done

**Comment by agrignard** [comment]
Well done!! Je suis curieux de savoir quel event tu gardes parmis les duplicates? bien joué regex en tout cas!

**Comment by agrignard** [comment]
I am checking day by day I notice a duplicate for Marché Gare for this event on the 14/02/2024
https://marchegare.fr/agenda/lankum

**Comment by tnguyenh** [comment]
Yep. One problem is when the event name is not the same. I can find three references to the same event:
- Lankum + Ensemble Parrenin
- LANKUM
- LANKUM + EMMANUELLE PARRENIN

The big issue with the scraping is to deal with error and inconsistencies from other sites.

Until now, the merge process compares the event name strings and find similarities.

**Comment by agrignard** [comment]
Concert de l'hostel Dieu vs Fugacités at la Rayonne 14/2/2024 appears twice
