### ISSUE TITLE
Data doc for data

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#18]
For information, currently this is the list of places that appears at least 3 times in the results of scrapex but that are not referenced or treated as valide places.

It needs to be step by step modified by hand either by adding the places if not existing in the following files:
https://github.com/agrignard/WhatsNext/blob/main/www/lyon_place.csv

or by editing the aliases of the places in this files https://github.com/agrignard/WhatsNext/blob/main/scraping/venues.json
and adding the corresponding aliases
exemple si ```Opéra National de Lyon```apparait ````Opéra de Lyon```` il faut ajouter ça 
`````
{
    "name": "Opéra National de Lyon",
    "country": "France",
    "city": "Lyon",
    "aliases": [
      "Opéra de Lyon"
    ]
  },
`````

`````
Place Salle Planete Culture : 175 fois
(index):203 Place Le Boui Boui : 92 fois
(index):203 Place Espace Gerson : 88 fois
(index):203 Place Theatre A L'ouest : 78 fois
(index):203 Place Cafe Theatre Le Complexe : 19 fois
(index):203 Place Le Nombril Du Monde : 16 fois
(index):203 Place Theatre De La Renaissance : 9 fois
(index):203 Place Salle Paul Garcin : 7 fois
(index):203 Place Theatre Theo Argence : 7 fois
(index):203 Place Théâtre de la Renaissance : 6 fois
(index):203 Place Centre Culturel L'aqueduc : 6 fois
(index):203 Place La Sucriere : 6 fois
(index):203 Place Groupama Stadium Lyon : 6 fois
(index):203 Place Salle Des Rancy : 5 fois
(index):203 Place Theatre De Venissieux (La Machinerie) : 5 fois
(index):203 Place L'intervalle : 5 fois
(index):203 Place Centre Culturel : 5 fois
(index):203 Place Centre Charlie Chaplin : 5 fois
(index):203 Place Les Grandes Locos : 5 fois
(index):203 Place Rita-Plage : 4 fois
(index):203 Place Vache Rouge : 4 fois
(index):203 Place L'agend'arts : 4 fois
(index):203 Place Salle Edouard Herriot : 4 fois
(index):203 Place Theatres Romains De Fourviere : 4 fois
(index):203 Place Theatre Comedie Odeon : 4 fois
(index):203 Place Le Repaire de la Comédie : 3 fois
(index):203 Place Théâtre Théo Argence : 3 fois
(index):203 Place Musée des Confluences : 3 fois
(index):203 Place Institut Lumière : 3 fois
(index):203 Place Théâtre Cinéma Jean Carmet : 3 fois
(index):203 Place Les Grandes Voisines : 3 fois
(index):203 Place O Totem Live : 3 fois
(index):203 Place Maison Du Peuple De Pierre Benite : 3 fois
(index):203 Place Espace Jean Poperen : 3 fois
(index):203 Place Chapelle De La Trinite : 3 fois
(index):203 Place Espace Culturel L'atrium : 3 fois
(index):203 Place Le Briscope : 3 fois
(index):203 Place Auditorium - Orchestre National De Lyon : 3 fois
(index):203 Place Theatre De Villefranche Sur Saone : 3 fois
(index):203 Place Heat (h7) : 3 fois
(index):203 Place Parc Naturel De Miribel Jonage : 3 fois
`````

2. Le Boui Boui is represented a lot because there are lots of event that play for long time  e.g https://www.infoconcert.com/ticket/concert-felix-le-braz-lyon/1642663.html
scrapex is doing well is job to create on event per day, however do we want to keep it? It seems that it's more like theater stuff? in general do we want to treat differently the event that are recurent?

3. Planète Culture a lots of event (175) but more or less always the same name, do we add it?

**Comment by tnguyenh** [comment]
Is it a problem to have many events ? It's easier to process in the app. Easier to process individual events than a global one.

Let's keep it now, we can always discard events later. We still don't have a business plan or any survey about needs, so let's keep everything for now.

**Comment by tnguyenh** [comment]
What did you scrap ? I don't see places such as Terminal or Le Sucre

**Comment by agrignard** [comment]
Yes yes in the scrapping process it's ok to have more then we can fillter (or create a cafe theatre style)
