### ISSUE TITLE
Default style in venues broken

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#19]
I am trying to put a default style to theatre for Espace Gerson like this

`````
{
    "name": "Espace Gerson",
    "country": "France",
    "city": "Lyon",
    "defaultStyle": "Theatre"
  }
`````

but it doesn't work maybe it needs other scrapping information? DefaultStyle is working for terminal for instance but there is more info in the srapping

**Comment by tnguyenh** [comment]
From where did you scrap ? Infoconcert ?

Currently, defaultStyle had been implemented for scrap sources, so actually it will look after the default style of infoconcerts. I will fix that.

**Comment by tnguyenh** [comment]
yes, keep it for Espace Gerson. Scrapex will look for:
first a style defined in the event;
if not defined, a default style from the place (Espace Gerson);
if not defined, a default style for the source (infoconcert, even if there should be no default style, but I will implement that as a placeholder, just in case)
finally, if no style is found, currently it is set to ''

**Comment by tnguyenh** [comment]
Fix to be tested
