### ISSUE TITLE
Give the possibility to define aliased style for place website scrap

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#20]
The alias style seems to work for generic site like petit bulletin, info concert but not for scrapped place

e.g lClubbing is well transformed to Electro for all the event from petit bulletin info concert etc but not if it's scrapped from le Sucre:

`````
Le Sucre;S.society x Dave Clarke 𝐩𝐫𝐞𝐬𝐞𝐧𝐭 𝐀𝐫𝐜𝐡𝐢𝐯𝐞 𝐎𝐧𝐞 𝐓𝐨𝐮𝐫 Dave Clarke NƵM 99;1707670800000;100;;Clubbing;https://le-sucre.eu/agenda/s-society-62/;11 fév. 18:00 — 00:00
`````

vs

`````
Le Sucre;Lumbago + Nicolas Lutz;1708293600000;100;Electro;Clubbing;https://www.petit-bulletin.fr/lyon/agenda-308833-lumbago-nicolas-lutz.html;Dimanche 18 février 2024 à 23h
`````

**Comment by tnguyenh** [comment]
Fixed. This possibility already exists, it was just a problem of case sensitive comparision.

**Comment by tnguyenh** [comment]
By the way, Infoconcert and Ville Morte list an event that doesn't exist on Le Sucre website...

"eventPlace": "Le Sucre",
    "eventName": "Clark",
    "eventDate": "10 février à 20:00",
    "eventStyle": "musique live",
    "eventURL": "https://villemorte.fr/agenda/clark/",
    "eventDetailedStyle": "musique live",
    "source": {
      "name": "Ville Morte",
      "city": "Lyon",
      "country": "France"
    },
    "unixDate": 1707591600000,
    "altURLs": [
      "https://villemorte.fr/agenda/clark/",
      "https://www.infoconcert.com/ticket/concert-clark-lyon/1622913.html"
    ]

**Comment by tnguyenh** [comment]
Ah it's cancelled, that's why...
