### ISSUE TITLE
Replace generic link with the place link

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#22]
We realized that having the link to le Petit Bulletin or Infoconcert is at then end not useful at all it because it doesn't give any more information of what we have so far (name, time , style) (ans it also shoes our sources...)

So what about (if easy to do) putting instead the link of the place? At least the user can go to the event page just by clicking few link. As it is you have the link to le petit bulletin but if you want to know more about the event you have to google it

**Comment by tnguyenh** [comment]
This is what I had proposed first... In that case, the url of the websites have to be declared in venues.json, a little bit of work for Data.

anyway in that case it may be useful to scrap the sites of the places, to avoid too many clicks. More user friendly.

**Comment by tnguyenh** [comment]
It's fixed. Other URLs are kept in key 'altURLs' just in case.
