### ISSUE TITLE
Generate an extra filed with a better date in the scraped results

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#27]
Is it possible for Regex to generate a more readable date string in order to generate a better UI in the final app

Currently we have this
<img width="236" alt="Screenshot 2024-02-26 at 12 14 15" src="https://github.com/agrignard/WhatsNext/assets/3928502/f2f4522e-2f95-45d9-b624-47a9a487a8f2">

At the end we could almost have only the hour as the date is the current day (maybe for now we keep something like dd/mm - hh:mm?)

**Comment by tnguyenh** [comment]
The last field of the csv is now the event time, with the format hh:mm.
The overall look of the information should be reworked ? With user language (french, english...)

**Comment by agrignard** [comment]
I see this kind of info

```Radiant-Bellevue;GISELLE(S) (Derouault / Pietragalla);1711567800000;100;;;http://radiant-bellevue.fr/;Date et horaires Mercredi 27 Mars 2024 à 20h30;02:30```
