### ISSUE TITLE
Special character problem (formerly: Better merge for the url link)

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#36]
When le petit bulletin or an original website have the same event we should have the link from the original event.

Today there is something at Periscope
https://www.periscope-lyon.com/concerts/trio-grande-shes-analog/

but whatsnext shoes this link:
https://www.petit-bulletin.fr/lyon/agenda-309134-trio-grande-she-s-analog.html

Is there a way to have a msarter merge that keep the original link if there is one?

**Comment by tnguyenh** [comment]
That's strange, it is supposed to work like that. I'm checking.

**Comment by tnguyenh** [comment]
OK, this has nothing to do with url: for some reason:
Trio Grande + She’s Analog
and 
Trio Grande + She’s Analog
are two different strings! So the event from 'Le Périscope' and 'Le Petit Bulletin' were not detected has the same. When opened with visual code, I have this:

![image](https://github.com/agrignard/WhatsNext/assets/18676913/d727b77a-cb2d-4c96-a509-dd50d7e687b1)

**Comment by tnguyenh** [comment]
fixed
