### ISSUE TITLE
Define default date when date cannot be extracted from event

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/WhatsNext#4]
Currently, when it is not possible extract a date ("du 23 au 25 janvier"), today's date is put in the csv by default.

The way to handle this, so it can be easily spotted in the csv,should be discussed.

**Comment by agrignard** [comment]
It shouldn't be today as we will have fake event. What about deleting the event? or pushing it to a past date?

**Comment by tnguyenh** [comment]
Deleting the event or pusing it to a past date is not a way to solve this. It can be done temporarilly while we wait for a better solution.

The difficulty is not to solve this problem, but to do it in a generic way, so we won't have to code for each site with a problem. Currently we can assume that there are common patterns. Let's list them here:

-  Vendredi 2 février 2024 de 18h à 22h
- Du 7 au 9 mars 2024, jeu à 20h, sam à 18h
- 9 mars et 10 mars sam à 20h, dim à 17h
- Du 13 février au 12 mars 2024, à 20h
- Du 17 au 23 mars 2024, dim et sam à 16h, lun, mar et ven à 20h, jeu à 19h30
- Du 16 mars au 3 avril 2024, à 19h30 sf dim à 16h
- Du 15 mars au 4 avril 2024, à 20h sf dim à 16h
- Mercredi 17 avril 2024 à 9h30 et 11h
- 3 février et 4 février sam à 18h, dim à 15h

Le Petit Bulletin is quite shity, since there is no consistency in the dates and times. And contrary to infoconcerts, there is no clear date list in the event list.

Some of the patterns can be processed in an automated way. However, we will arrive at the limit of automation. For the events for which some errors will remain, it will be the job of Data.

One last point: events like AYRON JONES + AMONGST LIARS seems to be better described on Transbordeur's site. 12 mars date doesn't seem to exist. Working on issue #11 will solve a part of the problem.

**Comment by tnguyenh** [comment]
All issues containing 'et' have been solved. Don't hesitate to report new ones. 

Issues 'du xx au xx' are impossible to solve automatically, because of inconsistencies (for example, du 13 février au 12 mars is not one month in a row...)

**Comment by tnguyenh** [comment]
Among 1881 events, only 6 events have problems and cannot be solved automatically (petit bulletin, du xx au xx). This won't be fixed and will need manual check by Data. Unixdate is set to 0 in that case.
