### ISSUE TITLE
Place to replace

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#5]
CCO- La Rayonne, CCO La Rayonne => La Rayonne
Toï Toï le zinc,Toï Toï le Zinc => Toï Toï Le Zinc
Épicerie Moderne=> Epicerie Moderne
Jack Jack - MJC Aragon => Jack Jack 
Bar Rock'n eat, Rock n Eat=> Rock N Eat
Amphithéâtre - Salle 3000=> Salle 3000
Grrrnd Zero =>  Grrrnd Zéro

**Comment by tnguyenh** [comment]
event a minuit
