### ISSUE TITLE
Handle Style

### ISSUE THREAD

**Issue by agrignard** [agrignard/WhatsNext#8]
So far I have created this file ```styleConversion.json```
buit not sure how to deal with this in scrapex

I guess it shoudl be around this part of the code
````
 eventInfo.eventStyle = venue.hasOwnProperty('defaultStyle')?venue.defaultStyle:globalDefaultStyle;
````

but I would prefer to check this with regex

**Comment by tnguyenh** [comment]
Did you push it ? I don't see the file

**Comment by agrignard** [comment]
yes sorry it has just been pusehed (it's just a skeleton)

**Comment by tnguyenh** [comment]
- you need to define a lot of keywords to list all the conversion possibilities. It is simple if there is a field with a style in the event. You should go through all the the scrapexresult.csv to get all patterns.
- it is complicated if there is no designated field for the event style. Take the Periscope, there is no style. Default style is currently "Jazz", which is wrong (see https://www.periscope-lyon.com/concerts/lumina/).

I propose to remove default style, but in that case, style will have to be defined manually, using info in the description. It is possible to search keywords also in the description, but it could lead to errors.

**Comment by agrignard** [comment]
Unknown could be if there is nothing.
For now the goal is to make a quick fix for the easy one like for instance but yes lots of pattern but to start with some of them are easy and cover lots of occurences

ÉLECTRO / TECHNO => Electro
RAP=>Rap
ROCK, POP FOLK, etc=>Rock

And yes for Periscope there is a default one which is not the best option but better than nothing no? We coudl remove the default style of course if scrapex can guess it that's great if not what? we keep an undefined style?

Indeed it will require to keep an dictionanry updated but at least we have a valide style in order to be displayed with a color in the mao

**Comment by agrignard** [comment]
Thank you regex! This one is done

**Comment by agrignard** [comment]
Is it possible in the alias do write something like

Any string that contains "Rock & Pop"  (e.g "Rock & Pop" / Metal, Rock & Pop / Folk Rock) be replaced by "Rock"

**Comment by tnguyenh** [comment]
so that would be "UNKNOWN":""
What is provided to the app is the key, not the list

I guess putting a wrong style is not good, since it appears in the wrong color and could be misleading. But updating missing styles should be data's work.

**Comment by tnguyenh** [comment]
You just need keywords in the list (you can use ["classique"] instead of ["classique & lyrique"].
There are also other types of events, like movies and théâtre. Should we include them ?
